version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/hexlabs-api
    steps:
    - checkout

    - restore_cache:
        keys:
        - gradle-{{ checksum "build.gradle.kts" }}

    - run:
        name: Gradle Clean
        command: ./gradlew clean

    - run:
        name: Gradle Build
        command: ./gradlew build -DBUILD_NUM=$CIRCLE_BUILD_NUM

    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-{{ checksum "build.gradle.kts" }}

    - run:
        name: Install KloudFormation
        command: curl -sSL install.kloudformation.hexlabs.io | bash -s -- -local

    - restore_cache:
        keys:
        - kloudformation-{{ checksum "kloudformation.sh" }}
    - run:
        name: Deploy Stack
        command:  ./kloudformation.sh -m serverless@0.1.13 deploy -stack-name hexlabs-api -location build/libs/hexlabs-api-0.1.$CIRCLE_BUILD_NUM-uber.jar -bucket hexlabs-deployments -output output.properties

    - store_artifacts:
        path: template.yml

    - store_artifacts:
        path: output.properties

    - save_cache:
        paths:
        - ~/.kloudformation
        key: kloudformation-{{ checksum "kloudformation.sh" }}