version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/hexlabs-api
    steps:
    - checkout
    - restore_cache:
        keys:
        - gradle-{{ checksum "build.gradle.kts" }}
    - run:
        name: Gradle Clean
        command: ./gradlew clean
    - run:
        name: Gradle Build
        command: ./gradlew build -DBUILD_NUM=$CIRCLE_BUILD_NUM
    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-{{ checksum "build.gradle.kts" }}
    - restore_cache:
        keys:
        - kloudformation-{{ checksum "kloudformation.sh" }}
    - run:
        name: Deploy Stack
        command: ./gradlew deployStacks
    - store_artifacts:
        path: build/template/template.yml
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: hexlabs-aws